// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $Buscar from "./routes/Buscar.tsx";
import * as $CrearPokemon from "./routes/CrearPokemon.tsx";
import * as $ListaPokemons from "./routes/ListaPokemons.tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Buscar_1 from "./islands/Buscar.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $PokemonManager from "./islands/PokemonManager.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/Buscar.tsx": $Buscar,
    "./routes/CrearPokemon.tsx": $CrearPokemon,
    "./routes/ListaPokemons.tsx": $ListaPokemons,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Buscar.tsx": $Buscar_1,
    "./islands/Counter.tsx": $Counter,
    "./islands/PokemonManager.tsx": $PokemonManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
